### ISSUE TITLE
Cotary Create: Stylings TODO's

### ISSUE THREAD

**Issue by mrrobot16** [dOrgTech/DAOcreator#318]
Here we are gonna list all pending styling details

- [x] Background color change on button when is validated
- [x] Distribute token toggle style
- [x] Input border color on focus
- [x] Token/distribution bars style
- [x] Member step style improvement
- [x] Member Avatar border needs to be rounded like in the mock ups
- [x] Metamask center text

**Comment by mrrobot16** [comment]
Add Margin For Please Add A Member
![AddMarginForPleaseAddAMember](https://user-images.githubusercontent.com/761735/73146328-0ad5d980-4080-11ea-972a-9f74f16bb5fa.png)

**Comment by mrrobot16** [comment]
After Inputs Filled Button Background Should Be Blue
![AfterInputsFilledButtonBackgroundShouldBeBlue-LikeInMockUps-App](https://user-images.githubusercontent.com/761735/73146341-1b864f80-4080-11ea-8646-d768168e4cc1.png)
Mockup:
![AfterInputsFilledButtonBackgroundShouldBeBlue-Mockup](https://user-images.githubusercontent.com/761735/73146342-1b864f80-4080-11ea-8888-aa3eb9b08a64.png)

**Comment by mrrobot16** [comment]
Distribute Token Toggle  how should this be styled
![DistributeTokenToggle-HowShouldThisBeStyled2?](https://user-images.githubusercontent.com/761735/73146359-32c53d00-4080-11ea-915e-f3c54fb64ac3.png)

**Comment by mrrobot16** [comment]
How should this be styled?

![ImportExportModal-HowShouldThisBeStyled?](https://user-images.githubusercontent.com/761735/73146392-61431800-4080-11ea-9afd-6bb51c67ce7c.png)

**Comment by mrrobot16** [comment]
Input border color when user focus like in mockups
![InputBorderColor-whenFocus](https://user-images.githubusercontent.com/761735/73146405-6d2eda00-4080-11ea-85fd-c729c586a9c6.png)

**Comment by mrrobot16** [comment]
Install Organization button has to be outside the box like in the mock ups.
![InstallOrgButton-HasToBeOutsideTheBox-LikeInMockUps](https://user-images.githubusercontent.com/761735/73146418-86d02180-4080-11ea-8f91-d98134b20a66.png)

**Comment by mrrobot16** [comment]
Install Step box should be more to left like in the mockups
![InstallStepBoxShouldBeMoreToLeft-LikeInMockUps](https://user-images.githubusercontent.com/761735/73146445-b2eba280-4080-11ea-851a-aad7263b8137.png)

**Comment by mrrobot16** [comment]
Line Graphics should start aligned with above text like in mock ups
![LineGraphicsNeedToBeAlignWithText-LikeInMockUps](https://user-images.githubusercontent.com/761735/73146634-bdf30280-4081-11ea-9074-7ea86e9f19c4.png)

**Comment by mrrobot16** [comment]
Need to add MarginTop to PreviewInfo's

![MarginTopForMembersPreviewInfo](https://user-images.githubusercontent.com/761735/73146674-e3800c00-4081-11ea-993e-e130f9155bbd.png)
![MarginTopforSchemePreviewInfo](https://user-images.githubusercontent.com/761735/73146675-e3800c00-4081-11ea-977d-8133f72f8d8d.png)

**Comment by mrrobot16** [comment]
Members box should be more to the left
![MembersBoxShouldBeMoreToLeft-LikeInMockUps](https://user-images.githubusercontent.com/761735/73146687-f4c91880-4081-11ea-8dc9-fc985d16cdc9.png)

**Comment by mrrobot16** [comment]
- Missing top row line above "Members", "Reputation", "Token" columns
- Avatar needs to be rounded like in the mock ups.

![MissingTopRowLineAboveMembersReputationToken-LikeInMockUps](https://user-images.githubusercontent.com/761735/73146724-10ccba00-4082-11ea-8a04-5dfeac82dba9.png)
